project:
  type: website
  output-dir: docs

website:
  title: "Publication-Ready Figure Generation in R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: qmd/prerequisites.qmd
        text: Prerequisites
      - href: qmd/setup.qmd
        text: Setup
    right:
      - icon: github
        href: https://github.com/DQBM-SIB/publication_ready_figs_R
  page-footer:
    right: "Copyright 2025, Deepak Tanwar"

format:
  html:
    theme: litera
    css: styles.css
    toc: true



